# Generated by Django 4.0.5 on 2023-03-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriety', '0003_location_details_location_latitude_location_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.JSONField(default=None, max_length=255),
        ),
    ]
