# Generated by Django 4.0.5 on 2022-12-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_useraccount_profilepicture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='DepartmentEmail',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
